apiVersion: v1
kind: Secret
metadata:
  name: orders-db
  namespace: retail-store
type: Opaque
stringData:
  RETAIL_ORDERS_PERSISTENCE_USERNAME: "dbadmin"
  RETAIL_ORDERS_PERSISTENCE_PASSWORD: "1q2w3e4r!"