apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: retail-eks-cluster
  region: ap-northeast-2
  version: "1.36"

iam:
  withOIDC: true

  vpcResourceControllerPolicy: true

vpc:
  id: ${VPC_ID} # vpc 바뀔때 마다 집어 넣어야함

  clusterEndpoints:
    publicAccess: true
    privateAccess: true

  publicAccessCIDRs:
    - 0.0.0.0/0 # 학원 ip가 아니면 못들어가나여?

  subnets:
    private:
      app-a:
        id: ${APP_a}
      app-c:
        id: ${APP_c}

managedNodeGroups:
  - name: retail-mgmt-node
    instanceType: t3.medium
    amiFamily: AmazonLinux2023

    minSize: 2
    desiredCapacity: 2
    maxSize: 2

    subnets:
      - app-a
      - app-c

    labels:
      workload: mgmt
      node-role: mgmt
    taints:
      - key: dedicated
        value: mgmt
        effect: NoSchedule

    volumeSize: 30
    volumeType: gp3

    tags:
      Name: retail-mgmt-node
      Tier: workernode
      Workload: mgmt

  - name: retail-app-node-1
    instanceType: t3.large
    amiFamily: AmazonLinux2023

    minSize: 1
    desiredCapacity: 1
    maxSize: 2

    subnets:
      - app-a

    privateNetworking: true

    labels:
      workload: app-a
      node-role: app-a

    volumeSize: 30
    volumeType: gp3

    tags:
      Name: retail-app-node-1
      Tier: workernode
      Workload: app-a

  - name: retail-app-node-2
    instanceType: t3.large
    amiFamily: AmazonLinux2023

    minSize: 1
    desiredCapacity: 1
    maxSize: 2

    subnets:
      - app-c

    privateNetworking: true

    labels:
      workload: app-c
      node-role: app-c

    volumeSize: 30
    volumeType: gp3

    tags:
      Name: retail-app-node-2
      Tier: workernode
      Workload: app-c

addons:
  - name: metrics-server
    configurationValues: |
      nodeSelector:
        workload: mgmt
      tolerations:
        - key: dedicated
          operator: Equal
          value: mgmt
          effect: NoSchedule
